version: 2

updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    directory: "/"
    reviewers:
      - "jrmash"
    schedule:
      interval: "daily"
